# Generated by Django 5.1.6 on 2025-03-03 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='paid',
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
    ]
