# Generated by Django 5.1.6 on 2025-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_bill_paid_bill_created_at_bill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
