# Generated by Django 5.1.6 on 2025-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('app', 'App Notification'), ('sms', 'SMS Notification'), ('email', 'Email Notification')], default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
