# Generated by Django 5.1.6 on 2025-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
