# Generated by Django 5.1.6 on 2025-02-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number_customuser_profile_picture'),
    ]

    operations = [
    ]
