# Generated by Django 5.1.6 on 2025-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
